// data/sampleJobs.ts

export const sampleJobs = [
    {
      id: 1,
      title: "Residential Electrician",
      company: "PowerTech Solutions",
      location: "New York, NY",
      type: "Full Time",
      budget: "Negotiable",
      urgent: true,
      tags: ["On-site", "Medical Insurance"],
      posted: "2 hours ago",
      logo: "P",
      services: ["Electrician"],
      radius: 15,
      duration: "30 days",
    },
    {
      id: 2,
      title: "Plumbing Contractor",
      company: "FlowMasters Inc",
      location: "Los Angeles, CA",
      type: "Contract",
      budget: "$5,000 - $8,000",
      urgent: true,
      tags: ["On-site", "Flexible Hours"],
      posted: "5 hours ago",
      logo: "F",
      services: ["Plumber"],
      radius: 25,
      duration: "14 days",
    },
    {
      id: 3,
      title: "Kitchen Renovation",
      company: "HomeReno Experts",
      location: "Chicago, IL",
      type: "Project-based",
      budget: "$12,000 - $15,000",
      urgent: false,
      tags: ["On-site", "Materials Provided"],
      posted: "1 day ago",
      logo: "H",
      services: ["Carpenter", "Plumber", "Electrician"],
      radius: 20,
      duration: "45 days",
    },
    {
      id: 4,
      title: "Commercial Painting",
      company: "ColorPro Services",
      location: "Houston, TX",
      type: "Contract",
      budget: "$7,000 - $10,000",
      urgent: true,
      tags: ["On-site", "Equipment Provided"],
      posted: "3 days ago",
      logo: "C",
      services: ["Painter"],
      radius: 30,
      duration: "21 days",
    },
    {
      id: 5,
      title: "HVAC Installation",
      company: "CoolAir Systems",
      location: "Miami, FL",
      type: "Full Time",
      budget: "Negotiable",
      urgent: false,
      tags: ["On-site", "Medical Insurance", "401k"],
      posted: "6 days ago",
      logo: "C",
      services: ["HVAC Technician"],
      radius: 15,
      duration: "Ongoing",
    },
    {
      id: 6,
      title: "Bathroom Remodeling",
      company: "LuxBath Designs",
      location: "Seattle, WA",
      type: "Project-based",
      budget: "$8,000 - $12,000",
      urgent: true,
      tags: ["On-site", "Flexible Hours"],
      posted: "4 days ago",
      logo: "L",
      services: ["Plumber", "Tile Installer"],
      radius: 10,
      duration: "30 days",
    },
  ]
  